##############################################################
##         Initial Encounter Configuration                  ##
## Script Generated for Undergrad class of microelectronics ##
## Generated by Matheus Moreira/Fernando Moraes - 2018      ##
##                                                          ##
## Functionalities of this script:                          ##
##  -Add filler cells to the design                         ##
##  -Generate a summary report of the final design          ##
##############################################################
##Add filler cells
add_fillers -base_cells FEED7 FEED5 FEED3 FEED25 FEED2 FEED15 FEED10 FEED1 -prefix FILLER
add_metal_fill
trim_metal_fill
##Generate reports
report_summary -out_dir summaryReport
